version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI="mongodb+srv://himejjad:Himjjad2025@media-app.cvkjgux.mongodb.net/?retryWrites=true&w=majority&appName=media-app"
      - AWS_ACCESS_KEY_ID="AKIAZMGKTHUC3L2AX4JP"
      - AWS_SECRET_ACCESS_KEY="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"
      - S3_BUCKET=media-app-bucket-us-east-1
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
